insert into todo ( id , description , is_completed , target_date ) values
(1, 'activity 1 from Class',FALSE, CURRENT_DATE()),
(2, 'activity 2', false, CURRENT_DATE() ),
(3, 'activity 3', true, CURRENT_DATE() ),
(4, 'activity 4', false, CURRENT_DATE() ),
(5, 'activity 5', true,CURRENT_DATE() ),
(6, 'activity 6 from Class',FALSE, CURRENT_DATE()),
(7, 'activity 7', false, CURRENT_DATE() ),
(8, 'activity 8', true, CURRENT_DATE() ),
(9, 'activity 9', false, CURRENT_DATE() ),
(10, 'activity 10', true,CURRENT_DATE() ),
(11, 'activity 11 from Class',FALSE, CURRENT_DATE()),
(12, 'activity 12', false, CURRENT_DATE() ),
(13, 'activity 13', true, CURRENT_DATE() ),
(14, 'activity 14', false, CURRENT_DATE() ),
(15, 'activity 15', true,CURRENT_DATE() ),
(16, 'activity 16 from Class',FALSE, CURRENT_DATE()),
(17, 'activity 17', false, CURRENT_DATE() ),
(18, 'activity 18', true, CURRENT_DATE() ),
(19, 'activity 19', false, CURRENT_DATE() ),
(20, 'activity 20', true,CURRENT_DATE() );